config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

  get 'posts/create'

  devise_for :users
  root 'pages#index'
  resources :pages
  resources :posts

  get '/home' => 'pages#home'

  get '/user/:id' => 'pages#profile'

  get '/explore' => 'pages#explore'

  get '/settings' => 'pages#settings'

  get '/friends' => 'pages#friends'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140}
  default_scope -> {order(created_at: :desc)}
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
    validates :follewer_id, presence: true
    
	belongs_to :followed, class_name: "User"
	validates :follewed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts, dependent: :destroy

         has_many :active_relationships, foreign_key: "follower_id", dependent: :destroy
         has_many :following, through: :active_relationships, source: :followed
         
         has_many :passive_relationships, foreign_key: "followed_id", dependent: :destroy
         has_many :followers, through: :passive_relationships, source: :follower

         def follow(other)
        	active_relationships.create(followed_id: other.id)
        	
         end
        
         def unfollow(other)
        	active_relationships.find_by(followed_id: other.id).destroy
        	
         end

         def following?(other)
        	following.include?(other)
        	
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

   protected #only app controller and affiliated controllers can access whats below it

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end


  def home
    @posts = Post.all
  end
    
  def profile
    if(User.find_by_username(params[:id]))
      @username = params[:id]
    else
      redirect_to root_path, :notice => "User not found!"
    end  
    @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newPost = Post.new
  end

  def explore
    @posts = Post.all
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  			
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/nav_user'%>
  <% else %>
  <%= render 'layouts/nav_guest' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">[ Tweeter ]</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">Home <span class="sr-only">(current)</span></a></li>
        <li class="active"><li><%= link_to "Music"  %></li><span class="sr-only">(current)</span></a></li>
        <li class="active"><li><%=link_to "Sports"  %></li><span class="sr-only">(current)</span></a></li>
        <li class="active"><li><%=link_to "News"  %></li><span class="sr-only">(current)</span></a></li>
        <li class="active"><li><%=link_to "Entertainment"  %></li><span class="sr-only">(current)</span></a></li>
        <li class="active"><li><%=link_to "Lifestyle"  %></li><span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">[ Tweeter ]</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", home_path %></a></li>
        <li><%= link_to "Explore", explore_path %></li>

      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
        
             <li><a href="/user/<%= current_user.username %>">profile</a></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><a href="/friends">Friends List</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


</body>
</html>

app/views/layouts/components/_post_form.html.erb
<%= form_for(@newPost) do |f| %>
<div class="field">
	<%= f.label :content %>
	<%= f.text_field :content, autofocus: true %>
</div>
<div class="actions">
	<%= f.submit "Tweet!" %>
</div>
<% end %>

app/views/pages/explore.html.erb
<h1>Pages#explore</h1>
<p>Find me in app/views/pages/explore.html.erb</p>

app/views/pages/friends.html.erb
friends.html.erb

app/views/pages/home.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
       <p>Tweets</p>
      </div>
    </div>
  </div>

  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">
      	<div class="container">
      	<form class="navbar-form navbar-left" role = "search">
      	  
           <div class="form-group">
            <input type="text" class="form-control" placeholder="What's Happening">
            <button type="submit" class="btn btn-default">Submit</button>
         </div>
         </div>
        </form>
      </div>
     <div class="panel-body">
       Your timeline is currently empty
     </div>
    </div>
  </div>

  <div class="col-xs-3">
    <div class="panel panel-default">
       <div class="panel-body">
         <p>Who to Follow</p>
       </div>
    </div>
   </div>
</div>
 

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/profile.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="jumbotron">
			<h2><%= current_user.username %></h2>
		</div>
	</div>
</div>
<div class="row">
  <div class="col-xs-3">
    <%= render 'layouts/components/post_form' %>
    <% for @p in @posts do %>
    <div class="panel panel-default">
      <div class="panel-body">
       <p> <%= @p.content %></p>
      </div>
    </div>
  <% end %>
  </div>

  <div class="col-xs-6">
    <div class="panel panel-default">
    
      	
     <div class="panel-body">
       Your timeline is currently empty
     </div>
    </div>
  </div>

  <div class="col-xs-3">
    <div class="panel panel-default">
       <div class="panel-body">
         <p>Who to Follow</p>
       </div>
    </div>
   </div>

   <div class="col-xs-3 col-xs-offset-9">
    <div class="panel panel-default">
       <div class="panel-body">
         <p>Trends</p>
       </div>
    </div>
   </div>
</div>

app/views/pages/settings.html.erb
friends.html.erb

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>